config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'to_dos#index'

  resources :users, only: [:new, :create, :edit, :update]
  resources :to_dos

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

  get 'calendar' => 'to_dos#calendar', as: :calendar
  get 'history' => 'to_dos#history', as: :history
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/to_do.rb
class ToDo < ApplicationRecord
  validates :title, :status, :due_date, :description, presence: true
  validates_length_of :description, maximum: 150

  belongs_to :user

  scope :pending, -> { where(status: 0) }
  scope :done, -> { where(status: 1) }

  def self.search(search)
    where("title ILIKE ?", "%#{search}%")
  end

  # For Simple Calendar gem
  def start_time
    self.due_date
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :email, uniqueness: true

  has_many :to_dos

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :load_to_do, only: [:show, :edit, :update, :destroy]

  def new
    @to_do = ToDo.new
  end

  def create
    @to_do = ToDo.new(to_do_params)
    @to_do.user = current_user

    if @to_do.save
      redirect_to to_dos_path, notice: "Task created!"
    else
      render :new
    end
  end

  def show
  end

  def index
    if !params[:search].blank?
      @upcoming_to_dos = ToDo.search(params[:search]).where(status: 0).order("due_date ASC")
      @completed_to_dos = ToDo.search(params[:search]).where(status: 1).order("due_date ASC")
    elsif current_user
      @upcoming_to_dos = current_user.to_dos.where(status: 0).order("due_date ASC")
      @completed_to_dos = current_user.to_dos.where(status: 1).order("due_date ASC")
    else
      redirect_to new_user_url, notice: "Sign up or log in to manage tasks."
    end
  end

  def edit
    if current_user != @to_do.user
      redirect_to :new, notice: "Not authorized."
    end
  end

  def update
    if @to_do.update_attributes(to_do_params)
      redirect_to to_dos_path, notice: "Task updated!"
    else
      render :edit
    end
  end

  def destroy
    @to_do.destroy

    redirect_to to_dos_url, notice: 'Task deleted.'
  end

  def calendar
    @to_dos = current_user.to_dos
  end

  def history
    if current_user
      @to_dos = current_user.to_dos.where(status: 1)
    else
      redirect_to new_user_url, notice: "Sign up or log in to manage tasks."
    end
  end

  private

  def load_to_do
    @to_do = ToDo.find(params[:id])
  end

  def to_do_params
    params.require(:to_do).permit(
      :title, :description, :due_date, :status, :user_id
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Welcome!"
    else
      render :new
    end
  end

  def edit
    if current_user != @user
      redirect_to :new, notice: "Not authorized."
    end
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to user_path(@user), notice: "Account updated!"
    else
      render :edit
    end
  end

  private

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email, :first_name, :last_name, :password, :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
      <a class="navbar-brand" href="/">ToDo</a>

      <%= form_tag(to_dos_url, method: "get", id: "search", class:"form-inline my-2 my-lg-0 ml-auto") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search by title", required: true, class: "form-control mr-sm-2", style: "width: 350px;" %>
        <%= submit_tag "Search", class:"btn btn-outline-primary my-2 my-sm-0" %>
      <% end %>

      <% if current_user %>
        <ul class="navbar-nav ml-auto">
          <li class="dropdown">
            <a class="" href="#" data-toggle="dropdown">
              <%= image_tag('user.svg', height:'32', width:'32') %>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item">
                <%= link_to "Tasks", to_dos_url, class: "nav-link" %>
              </li>
              <li class="dropdown-item">
                <%= link_to "Calendar", :calendar, class: "nav-link" %>
              </li>
              <li class="dropdown-item">
                <%= link_to "History", :history, class: "nav-link" %>
              </li>
              <li class="dropdown-item">
                <%= link_to "Account", edit_user_url(current_user), class: "nav-link" %>
              </li>
              <li class="dropdown-item">
                <%= link_to "Log Out", :logout, class: "nav-link" %>
              </li>
            </ul>
          </li>
        </ul>

      <% else %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", :login, class: "nav-link" %>
          </li>
        </ul>
      <% end %>
    </nav>

    <p class="text-center"><%= flash[:notice] %></p>

    <%= yield %>
  </body>
</html>

app/views/to_dos/_form.html.erb
<%= form_for(@to_do, url: { action: params[:action] == "edit" ? "update" : "create" }) do |f| %>
  <% if @to_do.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(@to_do.errors.count, "error") %> prohibited change!</h5>
      <ul>
      <% @to_do.errors.full_messages.each do |msg| %>
        <li class="error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title, placeholder: "Title", required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_field :description, placeholder: "Enter a description here..", required: true, class: "form-control", rows: 3 %>
  </div>

  <div class="form-group">
    <%= f.label :due_date, class: "form-label" %>
    <%= f.datetime_field :due_date, required: true, class: "form-control" %>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit "SUBMIT", class: 'btn btn-primary' %>

  <%= link_to "BACK", to_dos_url, class:"btn btn-outline-success" %>
<% end %>

app/views/to_dos/calendar.html.erb
<div class="container text-center">
  <div class="row mt-5 mb-5">
    <div class="col-12">
      <h1 class="mb-1">Weekly Schedule</h1>
    </div>
  </div>

  <div class="row mt-5 mb-5">
    <div class="col-12">
      <% if !current_user.to_dos.empty? %>
        <%= week_calendar events: @to_dos do |date, tasks| %>
          <%= date %>

          <% tasks.each do |event| %>
            <div>
              <%= link_to event.title, to_do_url(event) %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/to_dos/edit.html.erb
<div class="container text-center">
  <div class="row mt-5 mb-5">
    <div class="col-2"></div>
    <div class="col-8">
      <h1 class="mb-3">Edit Task</h1>

      <%= render 'form' %>
    </div>
    <div class="col-2"></div>
  </div>
</div>

app/views/to_dos/history.html.erb
<div class="container text-center">
  <div class="row mt-5 mb-5">
    <div class="col-12">
      <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action active">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Completed Tasks</h5>
          </div>
        </a>
        <% @to_dos.each do |task| %>
          <%= link_to edit_to_do_url(task), class: "list-group-item list-group-item-action text-left" do %>
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1"><%= task.title %></h5>
            </div>
            <p class="mb-1"><%= task.description %></p>
            <% if task.status == 0 %>
              <div class="text-danger">
            <% else %>
              <div class="text-primary">
            <% end %>
              <p class="mb-1"><%= task.due_date.localtime.strftime('%b %Y - %H:%M ') %></p>
            </div>
            <%= form_for task, method: :put do |f| %>
              <%= f.hidden_field :status, value: 1 %>
              <%= f.submit "Complete", class:"btn btn-primary mb-1" %>
            <% end %>
            <%= button_to "Delete", { action: "destroy", id: task.id },
              method: :delete, data: { confirm: "Are you sure you want to permanently delete this task?" },
              class: "btn btn-danger" %>
          <% end %>
        <% end %>
        <% if @to_dos.empty? %>
          <h5 class="mt-4 mb-1">Click <%= link_to "here", to_dos_url %> to start managing tasks.</h5>
        </a>
        <% end %>
      </div>
    </div>
  </div>


</div>

app/views/to_dos/index.html.erb
<div class="container text-center">
  <div class="row mt-5 mb-5">
    <div class="col-12">
      <%= link_to "New Task", new_to_do_path, class: "btn btn-outline-primary", style: "font-size: 18px;" %>
    </div>
  </div>

  <div class="row mt-5 mb-5">
    <div class="col-6">
      <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action active">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Upcoming Tasks</h5>
          </div>
        </a>
        <% @upcoming_to_dos.each do |task| %>
          <div class="list-group-item list-group-item-action text-left">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1"><%= task.title %></h5>
              <small><%= link_to "Edit", edit_to_do_url(task) %></small>
            </div>
            <p class="mb-1"><%= task.description %></p>
              <div class="text-danger">
              <p class="mb-1"><%= task.due_date.localtime.strftime('%b %Y - %H:%M ') %></p>
            </div>
            <%= form_for task, url: to_do_url(task), method: "patch" do |f| %>
              <%= f.hidden_field :status, value: 1 %>
              <%= f.submit "Complete", class:"btn btn-primary mb-1" %>
            <% end %>
            <%= button_to "Delete", { action: "destroy", id: task.id },
              method: :delete, data: { confirm: "Are you sure you want to permanently delete this task?" },
              class: "btn btn-danger" %>
          </div>
        <% end %>
        <% if @upcoming_to_dos.empty? %>
          <a href="#" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Click above to add tasks.</h5>
            </div>
          </a>
        <% end %>
      </div>
    </div>

    <div class="col-6">
      <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action active">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Completed Tasks</h5>
          </div>
        </a>
        <% @completed_to_dos.each do |task| %>
          <div class="list-group-item list-group-item-action text-left">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1"><%= task.title %></h5>
              <small><%= link_to "Edit", edit_to_do_url(task) %></small>
            </div>
            <p class="mb-1"><%= task.description %></p>
              <div class="text-primary">
              <p class="mb-1"><%= task.due_date.localtime.strftime('%b %Y - %H:%M ') %></p>
            </div>
            <%= form_for task, url: to_do_url(task), method: "patch" do |f| %>
              <%= f.hidden_field :status, value: 0 %>
              <%= f.submit "Incomplete", class:"btn btn-primary mb-1" %>
            <% end %>
            <%= button_to "Delete", { action: "destroy", id: task.id },
              method: :delete, data: { confirm: "Are you sure you want to permanently delete this task?" },
              class: "btn btn-danger" %>
          </div>
        <% end %>
        <% if @completed_to_dos.empty? %>
          <a href="#" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <!-- <h5 class="mb-1">Click above to add tasks.</h5> -->
            </div>
          </a>
        <% end %>
      </div>
    </div>
  </div>


</div>

app/views/to_dos/new.html.erb
<div class="container text-center">
  <div class="row mt-5 mb-5">
    <div class="col-2"></div>
    <div class="col-8">
      <h1 class="mb-3">Create Task</h1>

      <%= render 'form' %>
    </div>
    <div class="col-2"></div>
  </div>
</div>

app/views/to_dos/show.html.erb
<div class="container text-center">
  <div class="row mt-5 mb-5">
    <div class="col-12">
      <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action active">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Task Details</h5>
          </div>
        </a>
        <%= link_to edit_to_do_url(@to_do), class: "list-group-item list-group-item-action text-left" do %>
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= @to_do.title %></h5>
          </div>
          <p class="mb-1"><%= @to_do.description %></p>
          <% if @to_do.status == 0 %>
            <div class="text-danger">
          <% else %>
            <div class="text-primary">
          <% end %>
            <p class="mb-1"><%= @to_do.due_date.localtime.strftime('%b %Y - %H:%M ') %></p>
          </div>
          <%= form_for @to_do, method: :put do |f| %>
            <%= f.hidden_field :status, value: 1 %>
            <%= f.submit "Complete", class:"btn btn-primary mb-1" %>
          <% end %>
          <%= button_to "Delete", { action: "destroy", id: @to_do.id },
            method: :delete, data: { confirm: "Are you sure you want to permanently delete this task?" },
            class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row mt-5 mb-5">
    <div class="col-12">
      <%= link_to "BACK", :calendar, class:"btn btn-outline-success" %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, url: { action: params[:action] == "edit" ? "update" : "create" }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(@user.errors.count, "error") %> prohibited change!</h5>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li class="error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.email_field :email, placeholder: "Email", required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.password_field :password, placeholder: "Password", required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.password_field :password_confirmation, placeholder: "Confirm Password", required: true, class: "form-control" %>
  </div>

  <%= f.submit "SUBMIT", class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<div class="container text-center">
  <div class="row mt-5 mb-5">
    <div class="col-2"></div>
    <div class="col-8">
      <h1 class="mb-3">Account Settings</h1>

      <%= render 'form' %>
    </div>
    <div class="col-2"></div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container text-center">
  <div class="row mt-5 mb-5">
    <div class="col-2"></div>
    <div class="col-8">
      <h1 class="mb-3">Sign Up</h1>
      
      <%= render 'form' %>
    </div>
    <div class="col-2"></div>
  </div>
</div>